google.maps.__gjsload__('geometry', function(_){var ms=function(a,b){return Math.abs(_.Lc(b-a,-180,180))},ns=function(a,b,c,d,e){if(!d){c=ms(a.lng(),c)/ms(a.lng(),b.lng());if(!e)return e=Math.sin(_.fc(a.lat())),e=Math.log((1+e)/(1-e))/2,b=Math.sin(_.fc(b.lat())),_.gc(2*Math.atan(Math.exp(e+c*(Math.log((1+b)/(1-b))/2-e)))-Math.PI/2);a=e.fromLatLngToPoint(a);b=e.fromLatLngToPoint(b);return e.fromPointToLatLng(new _.P(a.x+c*(b.x-a.x),a.y+c*(b.y-a.y))).lat()}e=_.fc(a.lat());a=_.fc(a.lng());d=_.fc(b.lat());b=_.fc(b.lng());c=_.fc(c);return _.Lc(_.gc(Math.atan2(Math.sin(e)*
Math.cos(d)*Math.sin(c-b)-Math.sin(d)*Math.cos(e)*Math.sin(c-a),Math.cos(e)*Math.cos(d)*Math.sin(a-b))),-90,90)},os=_.n(),ps={containsLocation:function(a,b){var c=_.Lc(a.lng(),-180,180),d=!!b.get("geodesic"),e=b.get("latLngs"),f=b.get("map");f=!d&&f?f.getProjection():null;for(var g=!1,h=0,k=e.getLength();h<k;++h)for(var l=e.getAt(h),m=0,q=l.getLength();m<q;++m){var r=l.getAt(m),v=l.getAt((m+1)%q),u=_.Lc(r.lng(),-180,180),w=_.Lc(v.lng(),-180,180),x=Math.max(u,w);u=Math.min(u,w);(180<x-u?c>=x||c<u:
c<x&&c>=u)&&ns(r,v,c,d,f)<a.lat()&&(g=!g)}return g||ps.isLocationOnEdge(a,b)}};_.bb("PolyGeometry.containsLocation",ps.containsLocation);
ps.isLocationOnEdge=function(a,b,c){c=c||1E-9;var d=_.Lc(a.lng(),-180,180),e=b instanceof _.ph,f=!!b.get("geodesic"),g=b.get("latLngs");b=b.get("map");b=!f&&b?b.getProjection():null;for(var h=0,k=g.getLength();h<k;++h)for(var l=g.getAt(h),m=l.getLength(),q=e?m:m-1,r=0;r<q;++r){var v=l.getAt(r),u=l.getAt((r+1)%m),w=_.Lc(v.lng(),-180,180),x=_.Lc(u.lng(),-180,180),B=Math.max(w,x),E=Math.min(w,x);if(w=1E-9>=Math.abs(_.Lc(w-x,-180,180))&&(Math.abs(_.Lc(w-d,-180,180))<=c||Math.abs(_.Lc(x-d,-180,180))<=
c)){w=a.lat();x=Math.min(v.lat(),u.lat())-c;var F=Math.max(v.lat(),u.lat())+c;w=w>=x&&w<=F}if(w)return!0;if(180<B-E?d+c>=B||d-c<=E:d+c>=E&&d-c<=B)if(v=ns(v,u,d,f,b),Math.abs(v-a.lat())<c)return!0}return!1};_.bb("PolyGeometry.isLocationOnEdge",ps.isLocationOnEdge);var qs={computeHeading:function(a,b){var c=_.td(a),d=_.ud(a);a=_.td(b);b=_.ud(b)-d;return _.Lc(_.gc(Math.atan2(Math.sin(b)*Math.cos(a),Math.cos(c)*Math.sin(a)-Math.sin(c)*Math.cos(a)*Math.cos(b))),-180,180)}};_.bb("Spherical.computeHeading",qs.computeHeading);
qs.computeOffset=function(a,b,c,d){b/=d||6378137;c=_.fc(c);var e=_.td(a);a=_.ud(a);d=Math.cos(b);b=Math.sin(b);var f=Math.sin(e);e=Math.cos(e);var g=d*f+b*e*Math.cos(c);return new _.R(_.gc(Math.asin(g)),_.gc(a+Math.atan2(b*e*Math.sin(c),d-f*g)))};_.bb("Spherical.computeOffset",qs.computeOffset);
qs.computeOffsetOrigin=function(a,b,c,d){c=_.fc(c);b/=d||6378137;d=Math.cos(b);var e=Math.sin(b)*Math.cos(c);b=Math.sin(b)*Math.sin(c);c=Math.sin(_.td(a));var f=e*e*d*d+d*d*d*d-d*d*c*c;if(0>f)return null;var g=e*c+Math.sqrt(f);g/=d*d+e*e;var h=(c-e*g)/d;g=Math.atan2(h,g);if(g<-Math.PI/2||g>Math.PI/2)g=e*c-Math.sqrt(f),g=Math.atan2(h,g/(d*d+e*e));if(g<-Math.PI/2||g>Math.PI/2)return null;a=_.ud(a)-Math.atan2(b,d*Math.cos(g)-e*Math.sin(g));return new _.R(_.gc(g),_.gc(a))};
_.bb("Spherical.computeOffsetOrigin",qs.computeOffsetOrigin);qs.interpolate=function(a,b,c){var d=_.td(a),e=_.ud(a),f=_.td(b),g=_.ud(b),h=Math.cos(d),k=Math.cos(f);b=qs.gf(a,b);var l=Math.sin(b);if(1E-6>l)return new _.R(a.lat(),a.lng());a=Math.sin((1-c)*b)/l;c=Math.sin(c*b)/l;b=a*h*Math.cos(e)+c*k*Math.cos(g);e=a*h*Math.sin(e)+c*k*Math.sin(g);return new _.R(_.gc(Math.atan2(a*Math.sin(d)+c*Math.sin(f),Math.sqrt(b*b+e*e))),_.gc(Math.atan2(e,b)))};_.bb("Spherical.interpolate",qs.interpolate);
qs.gf=function(a,b){var c=_.td(a);a=_.ud(a);var d=_.td(b);b=_.ud(b);return 2*Math.asin(Math.sqrt(Math.pow(Math.sin((c-d)/2),2)+Math.cos(c)*Math.cos(d)*Math.pow(Math.sin((a-b)/2),2)))};qs.computeDistanceBetween=function(a,b,c){c=c||6378137;return qs.gf(a,b)*c};_.bb("Spherical.computeDistanceBetween",qs.computeDistanceBetween);qs.computeLength=function(a,b){b=b||6378137;var c=0;a instanceof _.fe&&(a=a.getArray());for(var d=0,e=a.length-1;d<e;++d)c+=qs.computeDistanceBetween(a[d],a[d+1],b);return c};
_.bb("Spherical.computeLength",qs.computeLength);qs.computeArea=function(a,b){return Math.abs(qs.computeSignedArea(a,b))};_.bb("Spherical.computeArea",qs.computeArea);qs.computeSignedArea=function(a,b){b=b||6378137;a instanceof _.fe&&(a=a.getArray());for(var c=a[0],d=0,e=1,f=a.length-1;e<f;++e)d+=qs.Cj(c,a[e],a[e+1]);return d*b*b};_.bb("Spherical.computeSignedArea",qs.computeSignedArea);qs.Cj=function(a,b,c){return qs.Dj(a,b,c)*qs.xk(a,b,c)};
qs.Dj=function(a,b,c){var d=[a,b,c,a];a=[];for(c=b=0;3>c;++c)a[c]=qs.gf(d[c],d[c+1]),b+=a[c];b/=2;d=Math.tan(b/2);for(c=0;3>c;++c)d*=Math.tan((b-a[c])/2);return 4*Math.atan(Math.sqrt(Math.abs(d)))};
qs.xk=function(a,b,c){a=[a,b,c];b=[];for(c=0;3>c;++c){var d=a[c],e=_.td(d);d=_.ud(d);var f=b[c]=[];f[0]=Math.cos(e)*Math.cos(d);f[1]=Math.cos(e)*Math.sin(d);f[2]=Math.sin(e)}return 0<b[0][0]*b[1][1]*b[2][2]+b[1][0]*b[2][1]*b[0][2]+b[2][0]*b[0][1]*b[1][2]-b[0][0]*b[2][1]*b[1][2]-b[1][0]*b[0][1]*b[2][2]-b[2][0]*b[1][1]*b[0][2]?1:-1};var rs={decodePath:function(a){for(var b=_.L(a),c=Array(Math.floor(a.length/2)),d=0,e=0,f=0,g=0;d<b;++g){var h=1,k=0;do{var l=a.charCodeAt(d++)-63-1;h+=l<<k;k+=5}while(31<=l);e+=h&1?~(h>>1):h>>1;h=1;k=0;do l=a.charCodeAt(d++)-63-1,h+=l<<k,k+=5;while(31<=l);f+=h&1?~(h>>1):h>>1;c[g]=new _.R(1E-5*e,1E-5*f,!0)}c.length=g;return c}};_.bb("PolylineCodec.decodePath",rs.decodePath);
rs.encodePath=function(a){a instanceof _.fe&&(a=a.getArray());return rs.Ll(a,function(b){return[Math.round(1E5*b.lat()),Math.round(1E5*b.lng())]})};_.bb("PolylineCodec.encodePath",rs.encodePath);rs.Ll=function(a,b){for(var c=[],d=[0,0],e,f=0,g=_.L(a);f<g;++f)e=b?b(a[f]):a[f],rs.Lh(e[0]-d[0],c),rs.Lh(e[1]-d[1],c),d=e;return c.join("")};rs.Lh=function(a,b){rs.Ml(0>a?~(a<<1):a<<1,b)};rs.Ml=function(a,b){for(;32<=a;)b.push(String.fromCharCode((32|a&31)+63)),a>>=5;b.push(String.fromCharCode(a+63))};_.y.google.maps.geometry={encoding:rs,spherical:qs,poly:ps};_.p=os.prototype;_.p.decodePath=rs.decodePath;_.p.encodePath=rs.encodePath;_.p.computeDistanceBetween=qs.computeDistanceBetween;_.p.interpolate=qs.interpolate;_.p.computeHeading=qs.computeHeading;_.p.computeOffset=qs.computeOffset;_.p.computeOffsetOrigin=qs.computeOffsetOrigin;_.Je("geometry",new os);});
